### ISSUE TITLE
Clearly mark Domains

### ISSUE THREAD

**Issue by parabolika66** [MyrionPhoenixmoon/scenarioo#40]
As a user I want to know what is documentation and what are planned changes so that I don't mix up things.

**Comment by parabolika66** [comment]
![150409-1_trennung_domaenen](https://cloud.githubusercontent.com/assets/10995253/7077301/f42ec8ee-df0f-11e4-8b40-9fbdceaa0765.jpg)

**Comment by adiherzog** [comment]
Good idea to use colors coding for the two application modes.

**Comment by bruderol** [comment]
Se my remarks on story #8 and email by @adiherzog about what we discussed and also about my proposal to use the (allready existing) power of special branch aliases in case a project wants to keep issues more clearly separated from pure documentation content. We should use the power of allready existing features instead of putting to much effort into this top level domain tab separation in the UI.

We propose to limit this story here (for the first version) to the most simplest solution: 
just use a special background color for new design-domain-related (issues/designs/sketches) content parts everywhere in the UI.

**Comment by MyrionPhoenixmoon** [comment]
We should use a pastel colour as background and see how that works out.

**Comment by parabolika66** [comment]
Estimate: 1h (define color scheme)
