### ISSUE TITLE
Define Repo Folder Structure and Create Dummy Issue XML files

### ISSUE THREAD

**Issue by parabolika66** [MyrionPhoenixmoon/scenarioo#50]
Create Issue XML files with dummy data. See #49 

Parent:
User story #42

**Comment by parabolika66** [comment]
Hey @MyrionPhoenixmoon 
Proposed folder structure:
![bildschirmfoto 2015-04-23 um 17 45 30](https://cloud.githubusercontent.com/assets/10995253/7301174/39074654-e9e1-11e4-8a6b-03ce96091e57.png)

**Comment by parabolika66** [comment]
My thoughts:
- SketchSteps should be named in increments of 1000, starting with 1000. Benefit: if a sketchStep is added between two existing sketchSteps, it can be named like this: sketchStep1 + (sketchStep2-sketchStep1)/2
- Like this the order of the sketchSteps is defined by their ASC order. A separate attribute in the XML file becomes obsolete.
- If a sketchStep is put to another position it needs to be renamed according to the above formula. In this case the sketch-folder (here: folder 1000), and both screenshots need renaming too. Is this performant (enough)? Could also be a problem as the originalScreenshot might be in use at the time of renaming. We need to think about this again. EDIT: Just realized that the originalScreenshots should not be renamed and renderedSketches are probably going to be created onSave anyway.
- In the sketch-folder X revisions of the sketch are being stored. Format needs to be defined. In my example it's SVG. By using the timestamp as filename, the current sketch is clearly marked. This could be the basis for a revision history later in the project / for another project.
- We need to define the date format for dateCreated / dateModified - UNIX timestamp? It's compact but not human readable (if someone should look directly into the XML files).

**Comment by parabolika66** [comment]
Dummy data: https://drive.google.com/open?id=0B_ws4NvlueKsb1hEUnZoUHB1V28&authuser=0

**Comment by adiherzog** [comment]
Two inputs:
- The "steps of 1000" approach has a problem: Between step 1000 and 2000 I can only insert 10 more steps. Therefore it's probably easier to just keep the order of the sketchSteps in the XML instead of dealing with corner cases that can happen in the proposed approach.
- XML usually uses dates in the following format: `<date>2014-09-14T03:02:26.560+02:00</date>`. There's probably not much you need to do if you just have a date field in a class and then serialize the class as XML. See also: http://www.w3schools.com/schema/schema_dtypes_date.asp
